
#define CHUNK_SIZE 64
#define CHUNK_NX 16
#define CHUNK_NY 6
#define CHUNK_NZ 16
#define BLOCK_NX (CHUNK_SIZE * CHUNK_NX)
#define BLOCK_NY (CHUNK_SIZE * CHUNK_NY)
#define BLOCK_NZ (CHUNK_SIZE * CHUNK_NZ)

#define USE_NEW_PRESENCE 0
