#pragma once

#define VOXEL_ACCEL_UNIFORMITY 1
#define ENABLE_DEPTH_PREPASS 1

#define CHUNK_FLAGS_ACCEL_GENERATED (1 << 0)

#define BRUSH_FLAGS_WORLD_BRUSH (1 << 1)
#define BRUSH_FLAGS_USER_BRUSH_A (1 << 2)
#define BRUSH_FLAGS_USER_BRUSH_B (1 << 3)
#define BRUSH_FLAGS_PARTICLE_BRUSH (1 << 4)
#define BRUSH_FLAGS_BRUSH_MASK (BRUSH_FLAGS_WORLD_BRUSH | BRUSH_FLAGS_USER_BRUSH_A | BRUSH_FLAGS_USER_BRUSH_B | BRUSH_FLAGS_PARTICLE_BRUSH)

#define LOG2_VOXEL_SIZE (-4)
#if LOG2_VOXEL_SIZE <= 0
#define VOXEL_SCL (1 << (-LOG2_VOXEL_SIZE))
#define VOXEL_SIZE (1.0 / VOXEL_SCL)
#else
#define VOXEL_SIZE (1 << LOG2_VOXEL_SIZE)
#define VOXEL_SCL (1.0 / VOXEL_SIZE)
#endif
#define CHUNK_WORLDSPACE_SIZE (float(CHUNK_SIZE) * float(VOXEL_SIZE))

#define PER_VOXEL_NORMALS 1
#define DITHER_NORMALS 0

#if LOG2_VOXEL_SIZE < -6
#error "this is not currently supported"
#endif
